FROM resin/%%RESIN_MACHINE_NAME%%-debian

RUN apt-get update \
	&& apt-get install -y \
		dnsmasq \
		rfkill \
		iw \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

ENV INITSYSTEM on

WORKDIR /usr/src/app

COPY dnsmasq.conf /etc/dnsmasq.conf
COPY interfaces /etc/network/interfaces

COPY start.sh .

CMD ["bash", "start.sh"]
